      SUBROUTINE XERMAX(MAX)                                            XER   10
C
C     ABSTRACT
C        XERMAX SETS THE MAXIMUM NUMBER OF TIMES ANY MESSAGE
C        IS TO BE PRINTED.  THAT IS, NON-FATAL MESSAGES ARE
C        NOT TO BE PRINTED AFTER THEY HAVE OCCURED MAX TIMES.
C        SUCH NON-FATAL MESSAGES MAY BE PRINTED LESS THAN
C        MAX TIMES EVEN IF THEY OCCUR MAX TIMES, IF ERROR
C        SUPPRESSION MODE (KONTRL=0) IS EVER IN EFFECT.
C
C        THE DEFAULT VALUE FOR MAX IS 10.
C
C     DESCRIPTION OF PARAMETER
C      --INPUT--
C        MAX - THE MAXIMUM NUMBER OF TIMES ANY ONE MESSAGE
C              IS TO BE PRINTED.
C
C     WRITTEN BY RON JONES, WITH SLATEC COMMON MATH LIBRARY SUBCOMMITTEE
C END OF ABSTRACT
C     LATEST REVISION ---  7 JUNE 1978
C
      JUNK = J4SAVE(4,MAX,.TRUE.)
      RETURN
      END
