      SUBROUTINE XSETUN(IUNIT)                                          XER   10
C
C     ABSTRACT
C        XSETUN SETS THE OUTPUT FILE TO WHICH ERROR MESSAGES ARE TO
C        BE SENT.  ONLY ONE FILE WILL BE USED.  SEE XSETUA FOR
C        HOW TO DECLARE MORE THAN ONE FILE.
C
C     DESCRIPTION OF PARAMETER
C      --INPUT--
C        IUNIT - AN INPUT PARAMETER GIVING THE LOGICAL UNIT NUMBER
C                TO WHICH ERROR MESSAGES ARE TO BE SENT.
C
C     WRITTEN BY RON JONES, WITH SLATEC COMMON MATH LIBRARY SUBCOMMITTEE
C END OF ABSTRACT
C     LATEST REVISION ---  7 JUNE 1978
C
      JUNK = J4SAVE(3,IUNIT,.TRUE.)
      JUNK = J4SAVE(5,1,.TRUE.)
      RETURN
      END
