jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      env:
        - UBUNTU_DISTRO=focal
        - DISTRO_PACKAGES="libqt5xmlpatterns5-dev"
    - os: linux
      dist: focal
      compiler: clang
      env:
        - UBUNTU_DISTRO=focal
        - DISTRO_PACKAGES="libqt5xmlpatterns5-dev"
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - UBUNTU_DISTRO=bionic
        - DISTRO_PACKAGES="libqt5xmlpatterns5-dev"
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - UBUNTU_DISTRO=xenial
        - DISTRO_PACKAGES=""

cache:
  - apt

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libxml2-dev libjsoncpp-dev gfortran qt5-default qtbase5-dev  $DISTRO_PACKAGES

 before_script:
   - cd ~/
   - git clone https://github.com/jhu-cisst/cisstNetlib
   - mkdir -p ~/cisstNetlib-build
   - mkdir -p ~/cisstNetlib-install
   - cd ~/cisstNetlib-build
   - cmake ~/cisstNetlib -DCMAKE_INSTALL_PREFIX=~/cisstNetlib-install
   - make install
   - mkdir -p ~/cisst-build
   - cd ~/cisst-build
   - cmake -C ~/build/jhu-cisst/cisst/.travis.cache.cmake ~/build/jhu-cisst/cisst

 script:
   - make
   - ls -lR lib
   - cd bin
   - ls -lR
   - ./cisstCommonTests -r
   - ./cisstVectorTests -r
   - ./cisstOSAbstractionTests -r
   - ./cisstParameterTypesTests -r
   - ./cisstNumericalTests -r

 notifications:
   email:
     - anton.deguet@jhu.edu
   on_success: change
   on_failure: always
